services:
  nerdcasheapp:
    container_name: NerdCashe_app
    build: ./NerdCasheFE
    image: nerdcashefe:v1
    environment:
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
    ports:
      - "3000:3000"
    networks:
      nerd-cashe-network:
        ipv4_address: 172.28.127.3
    volumes:
      - app-data:/var/www/html
  nerdcasheserver:
    build: ./NerdCasheBE
    container_name: NerdCasheBE
    depends_on:
      db:
        condition: service_healthy
    environment:
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
      DATABASE: ${DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: 172.28.127.1
      DB_PORT: ${DB_PORT}
      PORT: ${PORT}
    ports:
      - "4000:4000"
    networks:
      nerd-cashe-network:
        ipv4_address: 172.28.127.2
    volumes:
      - server-data:/var/
  db:
    image: postgres
    container_name: todo_db
    restart: always
    volumes:
      - ./NerdCasheBE/database/migrations/sql/1-nerd-cashe-dbcreation.sql:/docker-entrypoint-initdb.d/schema.sql
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "5432:5432"
    networks:
      nerd-cashe-network:
        ipv4_address: 172.28.127.1
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DATABASE}'"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  app-data:
  pg-data:
  server-data:
networks:
  nerd-cashe-network:
    ipam:
      config:
        - subnet: 172.28.0.0/16
