services:
  cloudflaretunnel:
    container_name: NerdCache-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      nerd-cashe-network:
        ipv4_address: 172.28.127.8
  nerdcacheapp:
    container_name: NerdCache_app
    build: ./NerdCacheFE
    image: nerdcachefe:v1
    restart: always
    environment:
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
      NODE_ENV: production
    ports:
      - "80:80"
    networks:
      nerd-cashe-network:
        ipv4_address: 172.28.127.7
    volumes:
      - app-data:/var/www/html
  nerdcacheserver:
    build: ./NerdCacheBE
    container_name: NerdCache-server
    image: nerdcachebe:v1
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
      DATABASE: ${DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: 172.28.127.5
      DB_PORT: ${DB_PORT}
      PORT: ${PORT}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      THEMOVIEDB_KEY: ${THEMOVIEDB_KEY}
    ports:
      - "3000:3000"
    networks:
      nerd-cashe-network:
        ipv4_address: 172.28.127.6
    volumes:
      - server-data:/var/
  db:
    image: postgres
    container_name: NerdCache_db
    restart: always
    volumes:
      - ./NerdCacheBE/database/migrations/sql/1-nerd-cache-dbcreation.sql:/docker-entrypoint-initdb.d/schema.sql
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "15432:5432"
    networks:
      nerd-cashe-network:
        ipv4_address: 172.28.127.5
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DATABASE}'"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  app-data:
  pg-data:
  server-data:
networks:
  nerd-cashe-network:
    ipam:
      config:
        - subnet: 172.28.0.0/16
